name: Test model image

on:
  workflow_run:
    workflows: ["Test and upload model"]
    types:
      - completed

jobs:
  test-image:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ersilia-os/ersilia-model-workflows/.github/workflows/test-model-image.yml@main
    with:
      repo_name: ${{ github.event.repository.name }}
      runner: ubuntu-latest
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  
  post-upload:
    needs: test-image
    if: needs.test-image.outputs.retag-success == 'success'
    uses: ersilia-os/ersilia-model-workflows/.github/workflows/post-model-upload.yml@main
    with:
      repo_name: ${{ github.event.repository.name }}
      runner: ubuntu-latest
    secrets:
      AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}