name: Test model on PR

on:
  pull_request:
    branches:
      - main

jobs:
  test-model-pr:
    if: github.repository != 'ersilia-os/eos-template'
    uses: ersilia-os/ersilia-model-workflows/.github/workflows/test-model-pr.yml@main
    with:
      branch: ${{ github.head_ref }}
      repo_name: ${{ github.event.repository.name }}
      pr_user: ${{ github.event.pull_request.user.login }}
      runner: ubuntu-latest
